function readConfig {
    param($cfgFile);

    $services = @();

    Get-Content -Path $cfgFile | %{
        ($serverName, $serviceName, $monitored) = $_ -split '\s*:\s*';
        $services += New-Object -TypeName PSObject -Property @{
            'serverName'  = $serverName;
            'serviceName' = $serviceName;
            'monitored'   = $monitored;
        }
    }

    return $services;
}

function checkService {
    param($service);

    $serviceObj = Get-Service -ComputerName $service.serverName -Name $service.serviceName -ErrorAction SilentlyContinue;

    if ($serviceObj.Status -ne 'Running')  {
        return 1;
    }

    return 0;

}

function generateAlertText {
    param($services);

    $classArr = @('even', 'odd');

    $message = '
    <!DOCTYPE html>
    <html>
	    <head>
            <style>
                tr.even {
                    background-color:lightblue;
                }
                tr.odd {
                    background-color:lightgrey;
                }
            </style>
	    </head>
	    <body>
            <h3>Service Down Alert</h3>
            <p>The following services are not currently running. Please check the status of each one and bring it online if necessary.</p>

		    <table cellspacing="0" style="width:100%">
			    <th align="left">Server Name</th>			    
			    <th align="left">Service Name</th>
                <th align="left">Executable</th>
';
    $counter = 1;
    foreach ($service in $services) {
        $execPath = getExecutable $service;

        $message += ('
        <tr class="{0}">
            <td>{1}</td>
            <td>{2}</td>
            <td>{3}</td>
        </tr>' -f $classArr[($counter % 2)], $service.serverName, $service.serviceName, $execPath);

        $counter++
    }
    
    $message += '
        </table>
        <h3>Service Start Instructions</h3>
        <p>To bring a service online, RDP to the server in question and open the "Services Manager" window. This can be done by typing "Services" into the run bar. Find the service in the list, right-click, and select "Start"</p>
        <p>If the service does not come online, and stay online, check the event log ("Event Viewer" in the run bar" for any relevant errors or clues, you may also need to check whatever logs are generated by the service in question</p>
        </body>
    </html>
    ';

    return $message;
}

function getExecutable {
    param($service);

    $execPath = Get-WmiObject win32_service -ComputerName $service.serverName | 
        ?{ $_.Name -like $service.serviceName } | 
        select PathName

    return $execPath.PathName;
}

function alert {
    param($message);

    #$creds    = createCred
    $toMail   = 'cgamble@psg340b.com';
    $fromMail = 'WebPortalMonitor@psg340b.com';
    $subject  = 'Web Portal Error';
    $body     = $message;
    $smtp     = 'smtp.office365.com'

    <#
    Send-MailMessage `
        -To $toMail `
        -From $fromMail `
        -Subject $subject `
        -Body $body `
        -SmtpServer $smtp `
        -Credential $creds;
    #>

    Write-Host $message;
}

#######################
#Main Block Below Here#
#######################
$cfgFile      = 'C:\temp\serviceMon.cfg';
$services     = readConfig $cfgFile;
$downServices = @();


foreach ($service in $services) {
    if (checkService $service) {
        $downServices += $service;
    }
}


if ($downServices) {
    $message = generateAlertText $downServices;
}
